# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jooyeon Jeong
title: Dr. degree with Physical Design of Very Large Scale Integrated (VLSI) Circuits
email: jooyeon@snucad.snu.ac.kr / jooyeon37@snu.ac.kr 
#linkedin: https://www.linkedin.com/in/jooyeon-jeong/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: https://www.linkedin.com/in/jooyeon-jeong/
linkedin_username: jooyeon-jeong
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Jooyeon Jeong. My research in digital semiconductor design focuses on Advanced Packaging and optimizing PPA(Power, Performance, Area) in the physical design stage, including standard cell design optimization, chip layout optimization and design-technology co-optimization, which considers both standard cells and chip layouts simultaneously. I have experiences with AI as well.

  I am most skilled in: <mark>Algorithm</mark>, <mark>Optimization</mark>, <mark>AI</mark>, <mark>Advanced Packaging</mark> and <mark>Electronic Design Automation</mark>

content:
  - title: Education and Employment
    layout: list
    content:
      - layout: left
        title: Postdoc
        sub_title: 2025-
        description: |
          University of California, Los Angeles
          Electrical and Computer Engineering
      - layout: left
        title: Ph. D
        sub_title: 2020-2025 
        description: |
          Seoul National University
          Electrical and Computer Engineering
      - layout: left
        title: Bachelor
        sub_title: 2016-2020
        description: |
          Chung-ang University
          Electrical and Electronics Engineering

  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ECTC'26 (Accepted)
        sub_title: Electronic Components and Technology Conference
        description: | # this will include new lines to allow paragraphs       
          Aaron Yen, Jooyeon Jeong and Puneet Gupta. <br>
          “Link Quality Aware Pathfinding for Chiplet Interconnects.” 
      - layout: left
        title: DATE'26 (Accepted)
        sub_title: Design, Automation and Test in Europe Conference
        description: | # this will include new lines to allow paragraphs       
          Junghyun Yoon, Jooyeon Jeong and Heechun Park. <br>
          “Breaking Standard Cell Margin Constraints for Area-Efficient VLSI Design.” 
      - layout: left
        title: MLCAD'25
        sub_title: International Symposium on Machine Learning for CAD
        description: | # this will include new lines to allow paragraphs       
          Jooyeon Jeong and Taewhan Kim. <br>
          “Machine Learning Driven Early Clustering for Multi-bit Flip-Flop Allocation.” 
      - layout: left
        title: DAC'24
        sub_title: Design Automation Conference 
        description: | # this will include new lines to allow paragraphs       
          Jooyeon Jeong and Taewhan Kim. <br>
          “Binding Multi-bit Flip-flop Cells through Design and Technology Co-optimization.” 
      - layout: left
        title: Integration'24
        sub_title: Integration, the VLSI Journal
        description: | # this will include new lines to allow paragraphs   
          Jooyeon Jeong and Taewhan Kim. <br>
          “Placement Legalization for Heterogeneous Cells of Non-Integer Multiple-Heights.”  
      - layout: left
        title: DATE'23
        sub_title: Design, Automation and Test in Europe Conference
        description: | # this will include new lines to allow paragraphs
          Jooyeon Jeong, Sehyeon Chung, Kyeongrok Jo, and Taewhan Kim. <br>
          “Synthesis and Utilization of Standard Cells Amenable to Gear Ratio of Gate-Metal Pitches for Improving Pin Accessibility.”  
      - layout: left
        title: ISLPED'22
        sub_title: International Symposium on Low Power Electronics and Design
        description: | # this will include new lines to allow paragraphs
          Sehyeon Chung, Jooyeon Jeong, and Taewhan Kim. <br>
          “Improving Performance and Power by Co-Optimizing Middle-of-Line Routing, Pin Pattern Generation, and Contact over Active Gates in Standard Cell Layout Synthesis.”  
      - layout: left
        title: ISOCC'21
        sub_title: International SoC Design Conference
        description: | # this will include new lines to allow paragraphs
          Heechun Park, Kyungjoon Chang, Jooyeon Jeong, Jaehoon Ahn, Ki-Seok Chung, and Taewhan Kim. <br>
          “Challenges on DTCO Methodology Towards Deep Submicron Interconnect Technology.”  
      - layout: left
        title: MWSCAS'21
        sub_title: Midwest Symposium on Circuits and Systems
        description: | # this will include new lines to allow paragraphs      
          Jooyeon Jeong and Taewhan Kim. <br>
          “Utilizing Middle-of-Line Resource in Filler Cells for Fixing Routing Failures.”  
      - layout: left
        title: MWSCAS'21
        sub_title: Midwest Symposium on Circuits and Systems
        description: | # this will include new lines to allow paragraphs
          Eunsol Jeong, Heechun Park, Jooyeon Jeong, and Taewhan Kim. <br>
          “Minimum Implant Area-Aware Threshold Voltage Refinement in Pre-Placement.”  
          
  - title: Work Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ASP-DAC conference
        sub_title: Local Arrangement Co-Chairs
        caption: January 2024
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            29th Asia and South Pacific Design Automation Conference
      - layout: left
        title: Samsung Electronics, System LSI
        sub_title: Intern
        caption: November 2022 - December 2022
        description: | # this will include new lines to allow paragraphs
            Conducted research on the utilization of mixed voltage threshold in standard cells for advanced circuit
      - layout: left
        title: Samsung Electronics
        sub_title: TA
        caption: October 17, 2024
        description: | # this will include new lines to allow paragraphs
            Conducted training on the overall usage of EDA tools for employees at Samsung Electronics. Particularly focused on hands-on exercises using multi-bit flip-flops.            
  - title: Projects and Collaborations
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FuriosaAI
        caption: July 31 2025
        description: | # this will include new lines to allow paragraphs
            Gave a seminar on using Graph Neural Networks (GNN) for multi-bit flip-flop clustering at FuriosaAI.
      - layout: left
        title: Samsung Electronics, Memory division
        caption: April 2022 - January 2024
        description: | # this will include new lines to allow paragraphs
            Memory-oriented standard cell exploration methodology for Design-Technology Co-Optimization(DTCO)
      - layout: left
        title: Samsung Electronics, LSI division
        caption: May 2022 - January 2024
        description: | # this will include new lines to allow paragraphs
            Design Optimization and Algorithm Development Using Non-Uniform Height Cell
      - layout: left
        title: Samsung Electronics, Foundry division
        caption: January 2021 - June 2023
        description: | # this will include new lines to allow paragraphs
            Investigated the integration of advanced DTCO methodologies to optimize standard cell technology, enhancing Power, Performance, and Area (PPA) of final chip designs
      - layout: left
        title: Samsung Electronics, SAIT division
        caption: September 2023
        description: | # this will include new lines to allow paragraphs
            Explored innovative solutions for physical design challenges in semiconductor manufacturing through the application of artificial intelligence
      - layout: left
        title: Cadence
        caption: November 2022
        description: | # this will include new lines to allow paragraphs
            Engaged in productive discussions and shared research findings with Cadence headquarters
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seoul National University
        caption: 2020 - 2025
        sub_title: M.S. & Ph.D Department of Electrical and Computer Engineering
        quote: >
          As a graduate student, I specialized in the physical design of digital circuits within semiconductor design. <br> In my remaining time before graduation, I plan to advance my research by applying AI to improve.
      - layout: left
        title: Chung-ang University
        caption: 2016 - 2020
        sub_title: B.S. School of Electrical and Electronics Engineering
        quote: >
          Entered as the class valedictorian / Full-tuition scholarship for four years (2016-2020) / <br> Academic Excellence Scholarship (2016-2018) / Departmental Scholarship (2016-2019) / Summa Cum Laude Graduate
 
  - title: Patent (ongoing)
    layout: list
    content:
      - layout: left    
        title: Inventor
        caption: 2024
        sub_title: Jooyeon Jeong and Taewhan Kim 
        quote: >     
          Non-Rectangular Multi-bit Flip-flop Composed of Flip-flops with Various Drive Strength
      
  - title: Research Interest
    layout: text
    content: | # this will include new lines to allow paragraphs
      - AI, Machine learning, Deep learning
      - Very-Large-Scale Integration (VLSI)
      - Physical design
      - Optimization                                                                                                                      
      - Algorithm
      
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Python
      - C/C++ 
      - SKILL language in Cadence 
      - AI, Machine learning, Deep learning                                                                                                                       
      
  - title: TA Experiences
    layout: list # Type of content section (list/text)
    content:
      - layout: middle
        title: Digital Logic Design
        caption: Fall 2023, Fall 2021, Summer 2021, Fall 2020
        description: | # this will include new lines to allow paragraphs
            Learn basic theories of logic design including Boolean algebra and logic minimization and operation principles of logic devices. It also covers design methods for combinational logic and sequential logic
      - layout: middle
        title: Fundamentals of algorithms
        caption: Fall 2024
        description: | # this will include new lines to allow paragraphs
            Learn various algorithms that are essential to analyze and solve complex problems systematically.

            

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
