# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jooyeon Jeong
title: PhD Candidate in Physical Design of Very Large Scale Integrated (VLSI) Circuits
email: jooyeon@snucad.snu.ac.kr / jooyeon37@snu.ac.kr 

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Jooyeon Jeong. My research in digital semiconductor design focuses on optimizing PPA(Power, Performance, Area) in the physical design stage, including standard cell design optimization, chip layout optimization and design-technology co-optimization, which considers both standard cells and chip layouts simultaneously. In my remaining time before graduation, I plan to advance my research by applying AI to improve.

  I am most skilled in: <mark>Algorithm</mark>, <mark>Optimization</mark> and <mark>Electronic Design Automation</mark>

content:
  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 2024 Design Automation Conference (DAC)
        description: | # this will include new lines to allow paragraphs       
          Jooyeon Jeong and Taewhan Kim. 
          “Binding Multi-bit Flip-flop Cells through Design and Technology Co-optimization.” 
      - layout: top-middle
        title: 2024 Integration, the VLSI Journal
        description: | # this will include new lines to allow paragraphs   
          Jooyeon Jeong and Taewhan Kim. 
          “Placement Legalization for Heterogeneous Cells of Non-Integer Multiple-Heights.”  
      - layout: top-middle
        title: 2023 Design, Automation and Test in Europe Conference (DATE)
        description: | # this will include new lines to allow paragraphs
          Jooyeon Jeong, Sehyeon Chung, Kyeongrok Jo, and Taewhan Kim. 
          “Synthesis and Utilization of Standard Cells Amenable to Gear Ratio of Gate-Metal Pitches for Improving Pin Accessibility.”  
      - layout: top-middle
        title: 2022 International Symposium on Low Power Electronics and Design (ISLPED)
        description: | # this will include new lines to allow paragraphs
          Sehyeon Chung, Jooyeon Jeong, and Taewhan Kim. 
          “Improving Performance and Power by Co-Optimizing Middle-of-Line Routing, Pin Pattern Generation, and Contact over Active Gates in Standard Cell Layout Synthesis.”  
      - layout: top-middle
        title: 2021 International SoC Design Conference (ISOCC)
        description: | # this will include new lines to allow paragraphs
          Heechun Park, Kyungjoon Chang, Jooyeon Jeong, Jaehoon Ahn, Ki-Seok Chung, and Taewhan Kim. 
          “Challenges on DTCO Methodology Towards Deep Submicron Interconnect Technology.”  
      - layout: top-middle
        title: 2021 Midwest Symposium on Circuits and Systems (MWSCAS)
        description: | # this will include new lines to allow paragraphs      
          Jooyeon Jeong and Taewhan Kim. 
          “Utilizing Middle-of-Line Resource in Filler Cells for Fixing Routing Failures.”  
      - layout: top-middle
        title: 2021 Midwest Symposium on Circuits and Systems (MWSCAS)
        description: | # this will include new lines to allow paragraphs
          Eunsol Jeong, Heechun Park, Jooyeon Jeong, and Taewhan Kim. 
          “Minimum Implant Area-Aware Threshold Voltage Refinement in Pre-Placement.”  
          
  - title: Work Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ASP-DAC conference
        sub_title: Local Arrangement Co-Chairs
        caption: January 2024
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            29th Asia and South Pacific Design Automation Conference
      - layout: left
        title: Samsung Electronics, System LSI
        sub_title: Intern
        caption: November 2022 - December 2022
        description: | # this will include new lines to allow paragraphs
            Conducted research on the utilization of mixed voltage threshold in standard cells for advanced circuit
            
  - title: Projects and Collaborations
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Samsung Electronics, Memory division
        caption: April 2022 - January 2024
        description: | # this will include new lines to allow paragraphs
            Memory-oriented standard cell exploration methodology for Design-Technology Co-Optimization(DTCO)
      - layout: left
        title: Samsung Electronics, LSI division
        caption: May 2022 - January 2024
        description: | # this will include new lines to allow paragraphs
            Design Optimization and Algorithm Development Using Non-Uniform Height Cell
      - layout: left
        title: Samsung Electronics, Foundry division
        caption: January 2021 - June 2023
        description: | # this will include new lines to allow paragraphs
            Investigated the integration of advanced DTCO methodologies to optimize standard cell technology, enhancing Power, Performance, and Area (PPA) of final chip designs
      - layout: left
        title: Samsung Electronics, SAIT division
        caption: September 2023
        description: | # this will include new lines to allow paragraphs
            Explored innovative solutions for physical design challenges in semiconductor manufacturing through the application of artificial intelligence
      - layout: left
        title: Cadence
        caption: November 2022
        description: | # this will include new lines to allow paragraphs
            Engaged in productive discussions and shared research findings with Cadence headquarters
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seoul National University
        caption: 2020 - 2025
        sub_title: M.S. & Ph.D Department of Electrical and Computer Engineering
        quote: >
          As a graduate student, I specialized in the physical design of digital circuits within semiconductor design. In my remaining time before graduation, I plan to advance my research by applying AI to improve.
      - layout: left
        title: Chung-ang University
        caption: 2016 - 2020
        sub_title: B.S. School of Electrical and Electronics Engineering
        quote: >
          Entered as the class valedictorian / Full-tuition scholarship for four years (2016-2020) / Academic Excellence Scholarship (2016-2018) / Departmental Scholarship (2016-2019) / Summa Cum Laude Graduate

  - title: Research Interest
    layout: text
    content: | # this will include new lines to allow paragraphs
      - AI, Machine learning, Deep learning
      - Very-Large-Scale Integration (VLSI)
      - Physical design
      - Optimization                                                                                                                      
      - Algorithm
      
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Python
      - C/C++ 
      - SKILL language in Cadence 
      - AI, Machine learning, Deep learning                                                                                                                       
      - TOEIC : 965
      - TOEIC Speaking : level 7
      - OPIC : IH
      
  - title: TA Experiences
    layout: list # Type of content section (list/text)
    content:
      - layout: middle
        title: Digital Logic Design
        caption: Fall 2023, Fall 2021, Summer 2021, Fall 2020
        description: | # this will include new lines to allow paragraphs
            Learn basic theories of logic design including Boolean algebra and logic minimization and operation principles of logic devices. It also covers design methods for combinational logic and sequential logic

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
